apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base

# Optional: override tag without editing deployments
images:
  - name: ghcr.io/myugan/shopwave-order-service
    newName: ghcr.io/myugan/shopwave-order-service
    newTag: latest
  - name: ghcr.io/myugan/shopwave-web
    newName: ghcr.io/myugan/shopwave-web
    newTag: latest
  - name: ghcr.io/myugan/shopwave-notification-service
    newName: ghcr.io/myugan/shopwave-notification-service
    newTag: latest
