apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-service-data
  namespace: production
  labels:
    app.kubernetes.io/name: order-service
    app.kubernetes.io/part-of: shopwave
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
